name: İyileştirme isteği
description: Şablonlar, matrisler veya kanıt iş akışı için geliştirme öner.
title: "[Öneri]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem tanımı
      description: Hangi problemi çözüyor?
      placeholder: Boşluğu / ihtiyacı açıklayın.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Önerilen çözüm
      description: Ne eklenmesini/değişmesini öneriyorsunuz?
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Kanıt / kaynaklar
      description: Otoritatif kaynak linkleri verin (AB mevzuat metni, Komisyon rehberi, standart vb.).
      placeholder: URL + kısa not.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatifler
      description: Düşündüğünüz diğer yaklaşımlar.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Kontrol listesi
      options:
        - label: Bu öneri kanıta dayalıdır (kaynaklar eklendi).
          required: true
        - label: Mükerrer olmaması için mevcut issue'ları kontrol ettim.
          required: true